package engine

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Oein/publix/internal/buildlog"
	"github.com/Oein/publix/internal/compose"
	"github.com/Oein/publix/internal/store"
	"github.com/Oein/publix/internal/traefik"
	"gopkg.in/yaml.v3"
)

// startCompose brings up a Compose stack.
//
// publix does not rewrite the user's compose file. It writes a second file
// containing only its own additions — labels, environment, shared volumes —
// and hands both to Compose, which merges them. The repository's file stays
// the authority on what the stack is; publix only says how it is wired into
// the platform.
func (e *Engine) startCompose(ctx context.Context, dc *Context) ([]string, error) {
	sp := dc.Spec
	base := filepath.Join(dc.Root, sp.Compose)
	project := traefik.ComposeProject(dc.Project.Slug)
	dc.Service = traefik.ServiceName(dc.Project.Slug, traefik.ComposeDeploymentKey)

	f, err := compose.Parse(base)
	if err != nil {
		return nil, err
	}

	overridePath, err := e.writeComposeOverride(dc, f)
	if err != nil {
		return nil, err
	}

	dc.Log.Printf("Bringing up the compose stack %q (%d service(s))", project, len(f.Services))
	args := []string{
		"compose",
		"--project-name", project,
		"--project-directory", dc.Root,
		"-f", base,
		"-f", overridePath,
		"up", "--detach", "--remove-orphans",
	}
	if f.HasBuild() {
		args = append(args, "--build")
	}
	if err := e.composeCmd(ctx, dc, 45*time.Minute, args...); err != nil {
		return nil, err
	}

	// Compose puts every service on its own project network. Traefik lives
	// on the shared publix network, so the routed containers have to be
	// attached to it as well. Doing this after the fact rather than in the
	// override avoids fighting Compose's list-merge rules for `networks`,
	// which would otherwise silently drop the stack's internal wiring.
	routed, err := e.attachComposeNetwork(ctx, dc, project)
	if err != nil {
		return nil, err
	}
	return routed, nil
}

// writeComposeOverride generates publix's additions to the stack. It lives
// outside the checkout so a build never dirties the repository.
func (e *Engine) writeComposeOverride(dc *Context, f *compose.File) (string, error) {
	env, err := e.buildEnv(dc)
	if err != nil {
		return "", err
	}
	binds, err := e.resolveVolumes(dc)
	if err != nil {
		return "", err
	}
	for _, b := range binds {
		dc.Log.Printf("Mounting shared volume %q at %s", b.Volume, b.MountPath)
	}

	meta := traefik.Meta{
		ProjectID:  dc.Project.ID,
		Slug:       dc.Project.Slug,
		Deployment: dc.Deployment.ID,
		Port:       dc.Spec.Port,
		Commit:     dc.Deployment.Commit,
		Branch:     dc.Deployment.Branch,
		Kind:       string(dc.Spec.Kind),
		Created:    time.Now().UTC().Format(time.RFC3339),
	}

	// Routed services are the ones a hostname points at: the primary
	// service, plus anything a route names explicitly.
	routed := map[string]bool{dc.Spec.Service: true}
	for _, r := range dc.Spec.Routes {
		if r.Service != "" {
			routed[r.Service] = true
		}
	}

	envMapping := envMap(env)
	services := map[string]any{}

	for _, name := range f.ServiceNames() {
		svc := map[string]any{}
		labels := traefik.BaseLabels(meta, traefik.RoleCompose)
		labels["com.docker.compose.service"] = name

		if routed[name] {
			// The Traefik service name is stable across deploys for a
			// compose stack, so the routing file does not change when the
			// stack is redeployed in place.
			key := traefik.ComposeDeploymentKey
			svcName := traefik.ServiceName(dc.Project.Slug, key)
			if name != dc.Spec.Service {
				svcName = traefik.ServiceName(dc.Project.Slug+"-"+traefik.Slug(name), key)
			}
			port := dc.Spec.Port
			if name != dc.Spec.Service {
				port = firstPortOf(f, name, port)
			}
			for k, v := range composeRouterLabels(&dc.Settings, svcName, port) {
				labels[k] = v
			}
		} else {
			labels["traefik.enable"] = "false"
		}

		svc["labels"] = labels
		if len(envMapping) > 0 {
			svc["environment"] = envMapping
		}
		if mounts := bindsForService(binds, name); len(mounts) > 0 {
			vols := make([]string, 0, len(mounts))
			for _, b := range mounts {
				vols = append(vols, b.String())
			}
			svc["volumes"] = vols
		}
		services[name] = svc
	}

	doc := map[string]any{"services": services}
	raw, err := yaml.Marshal(doc)
	if err != nil {
		return "", err
	}
	header := []byte("# Generated by publix. Merged over your compose file at deploy time.\n" +
		"# Your repository is never modified; this file lives outside the checkout.\n")

	dir := filepath.Join(e.store.Settings().WorkDir, ".overrides")
	if err := ensureDir(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, dc.Project.ID+".compose.yml")
	// 0600: the override carries the project's environment, secrets included.
	if err := os.WriteFile(path, append(header, raw...), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// composeRouterLabels are the Traefik labels for a routed compose service.
func composeRouterLabels(set *store.Settings, svcName string, port int) map[string]string {
	l := map[string]string{
		"traefik.enable":         "true",
		"traefik.docker.network": set.Network,
	}
	if port > 0 {
		l["traefik.http.services."+svcName+".loadbalancer.server.port"] = itoa(port)
	}
	return l
}

// attachComposeNetwork connects the stack's routed containers to the shared
// publix network and returns their IDs for the health gate.
func (e *Engine) attachComposeNetwork(ctx context.Context, dc *Context, project string) ([]string, error) {
	containers, err := e.docker.ListContainers(ctx, true, "com.docker.compose.project="+project)
	if err != nil {
		return nil, err
	}
	if len(containers) == 0 {
		return nil, fmt.Errorf("compose reported success but started no containers for %q", project)
	}

	routed := map[string]bool{dc.Spec.Service: true}
	for _, r := range dc.Spec.Routes {
		if r.Service != "" {
			routed[r.Service] = true
		}
	}

	var out []string
	for _, c := range containers {
		service := c.Labels["com.docker.compose.service"]
		if !routed[service] {
			continue
		}
		aliases := []string{dc.Project.Slug + "-" + traefik.Slug(service)}
		if service == dc.Spec.Service {
			aliases = append(aliases, dc.Project.Slug)
		}
		if err := e.docker.ConnectNetwork(ctx, dc.Settings.Network, c.ID, aliases); err != nil {
			return nil, fmt.Errorf("attaching %s to the %q network: %w", c.Name(), dc.Settings.Network, err)
		}
		out = append(out, c.ID)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("compose service %q started no containers", dc.Spec.Service)
	}
	sort.Strings(out)
	return out, nil
}

// rollbackCompose is the failure path for a compose deploy.
//
// Unlike a Dockerfile deploy, there is no untouched previous generation to
// fall back to: Compose replaced the containers in place. The honest thing
// is to say so rather than pretend a rollback happened, and to leave the
// stack up so its logs can be read.
func (e *Engine) rollbackCompose(ctx context.Context, dc *Context) {
	dc.Log.Printf("This compose stack was replaced in place, so there is no previous generation to restore.")
	dc.Log.Printf("The stack has been left running so you can inspect it. Roll back to a previous deployment to rebuild it from that commit.")
}

// ComposeDown removes a compose stack entirely. Named volumes are kept
// unless volumes is set, because destroying a stack's data is a decision
// that has to be made explicitly.
func (e *Engine) ComposeDown(ctx context.Context, slug string, volumes bool) error {
	args := []string{"compose", "--project-name", traefik.ComposeProject(slug), "down", "--remove-orphans"}
	if volumes {
		args = append(args, "--volumes")
	}
	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Env = append(os.Environ(), "COMPOSE_PROGRESS=plain")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("docker compose down: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

// composeCmd runs a docker compose command, relaying its output live.
func (e *Engine) composeCmd(ctx context.Context, dc *Context, timeout time.Duration, args ...string) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	stdout := dc.Log.Writer(buildlog.StreamStdout)
	stderr := dc.Log.Writer(buildlog.StreamStderr)
	defer stdout.Flush()
	defer stderr.Flush()

	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = dc.Root
	cmd.Env = append(os.Environ(),
		"COMPOSE_PROGRESS=plain", // interactive progress renders as noise in a log
		"DOCKER_BUILDKIT=1",
		"COMPOSE_DOCKER_CLI_BUILD=1",
	)
	cmd.Stdout, cmd.Stderr = stdout, stderr

	if err := cmd.Run(); err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			return fmt.Errorf("docker compose %s timed out after %s", args[1], timeout)
		}
		return fmt.Errorf("docker compose %s failed: %w", argAfterFlags(args), err)
	}
	return nil
}

// argAfterFlags names the compose subcommand for an error message.
func argAfterFlags(args []string) string {
	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "--project-name", "--project-directory", "-f":
			i++
		default:
			return args[i]
		}
	}
	return "compose"
}

func firstPortOf(f *compose.File, service string, fallback int) int {
	if svc, ok := f.Services[service]; ok {
		sub := compose.File{Services: map[string]compose.Service{service: svc}}
		if _, p := sub.Guess(); p > 0 {
			return p
		}
	}
	return fallback
}

func itoa(n int) string { return strconv.Itoa(n) }
