package framework

import (
	"fmt"
	"strings"
)

// Overrides let deployment.yaml adjust a generated Dockerfile without
// having to write the whole thing.
type Overrides struct {
	Install string
	Build   string
	Start   string
	Output  string
	Builder string
	Runtime string
	Port    int
	SPA     *bool
}

// Apply layers overrides onto a detection result.
func (r *Result) Apply(o Overrides) *Result {
	out := *r
	for dst, src := range map[*string]string{
		&out.Install: o.Install,
		&out.Build:   o.Build,
		&out.Start:   o.Start,
		&out.Output:  o.Output,
		&out.Builder: o.Builder,
		&out.Runtime: o.Runtime,
	} {
		if src != "" {
			*dst = src
		}
	}
	if o.Port > 0 {
		out.Port = o.Port
	}
	if o.SPA != nil {
		out.SPA = *o.SPA
	}
	// An explicit start command means a server, whatever was detected —
	// it is the clearest statement a user can make about how this runs.
	if o.Start != "" {
		out.Mode = ModeServer
	}
	return &out
}

// Render produces the Dockerfile for a detected project.
//
// The generated file is injected into the build context at build time and
// never written to the repository. A user who wants control commits their
// own Dockerfile, and publix defers to it entirely.
func (r *Result) Render() ([]byte, error) {
	switch {
	case r.Mode == ModeStatic:
		return r.renderStatic()
	case r.ID == "go":
		return r.renderGo()
	case r.ID == "python" || r.ID == "django" || r.ID == "fastapi" || r.ID == "flask":
		return r.renderPython()
	case r.Node != nil:
		return r.renderNode()
	default:
		return nil, fmt.Errorf("publix has no build template for %s", r.Name)
	}
}

// header explains where the file came from, since it shows up in build logs.
func header(name string) string {
	return "# Generated by publix for " + name + ".\n" +
		"# This file is built from the repository's configuration and is never\n" +
		"# written to your repository. Commit your own Dockerfile to take over.\n" +
		"# syntax note: keep dependency layers before source so a code-only\n" +
		"# change does not reinstall the world.\n"
}

// renderNode builds a JavaScript server: dependencies, then build, then a
// runtime stage that reinstalls only production dependencies.
func (r *Result) renderNode() ([]byte, error) {
	n := r.Node
	if n == nil {
		return nil, fmt.Errorf("no Node toolchain was detected")
	}
	if r.Start == "" {
		return nil, fmt.Errorf("publix does not know how to start this app; set build.start in deployment.yaml")
	}

	var b strings.Builder
	b.WriteString(header(r.Name))

	// Stage 1: dependencies. Copying only the manifest and lockfile first
	// is what lets Docker skip the install on a code-only change.
	fmt.Fprintf(&b, "\nFROM %s AS deps\nWORKDIR /app\n", r.Builder)
	writeManagerSetup(&b, n)
	fmt.Fprintf(&b, "%s\nRUN %s\n", n.lockfileCopy(), n.Install)

	// Stage 2: build.
	fmt.Fprintf(&b, "\nFROM %s AS build\nWORKDIR /app\n", r.Builder)
	writeManagerSetup(&b, n)
	b.WriteString("COPY --from=deps /app/node_modules ./node_modules\nCOPY . .\n")
	b.WriteString("ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 NUXT_TELEMETRY_DISABLED=1 ASTRO_TELEMETRY_DISABLED=1 CI=1\n")
	if r.Build != "" {
		fmt.Fprintf(&b, "RUN %s\n", r.Build)
	}

	// Stage 3: runtime.
	fmt.Fprintf(&b, "\nFROM %s AS runtime\nWORKDIR /app\n", r.Runtime)
	b.WriteString("ENV NODE_ENV=production PORT=" + itoa(r.Port) + "\n")
	writeManagerSetup(&b, n)

	if r.Standalone {
		// Next.js standalone output carries its own minimal node_modules,
		// so nothing else needs to come across. This is the difference
		// between a ~150MB image and a ~1GB one.
		b.WriteString("# Next.js standalone output: only the server and its assets.\n")
		b.WriteString("COPY --from=build /app/.next/standalone ./\n")
		b.WriteString("COPY --from=build /app/.next/static ./.next/static\n")
		b.WriteString("COPY --from=build /app/public* ./public\n")
	} else {
		// Reinstalling production dependencies drops devDependencies,
		// which are usually the bulk of a node_modules tree.
		fmt.Fprintf(&b, "%s\nRUN %s\n", n.lockfileCopy(), productionInstall(n))
		b.WriteString("COPY --from=build /app ./\n")
	}

	b.WriteString("\n# Run unprivileged: the node image ships a `node` user for this.\n")
	b.WriteString("RUN chown -R node:node /app\nUSER node\n")
	fmt.Fprintf(&b, "EXPOSE %d\n", r.Port)
	fmt.Fprintf(&b, "CMD [\"sh\", \"-c\", %s]\n", quote(startCommand(r)))
	return []byte(b.String()), nil
}

// startCommand is the runtime command, with standalone Next.js special-cased
// because its entry point is a generated server.js rather than `next start`.
func startCommand(r *Result) string {
	if r.Standalone && r.ID == "nextjs" {
		return "node server.js"
	}
	return r.Start
}

// productionInstall drops devDependencies from the runtime image.
func productionInstall(n *Node) string {
	switch n.Manager {
	case "pnpm":
		if n.Lockfile == "" {
			return "pnpm install --prod --no-frozen-lockfile"
		}
		return "pnpm install --prod --frozen-lockfile"
	case "yarn":
		return "yarn install --production"
	case "bun":
		return "bun install --production"
	default:
		if n.Lockfile == "" {
			return "npm install --omit=dev"
		}
		return "npm ci --omit=dev"
	}
}

func writeManagerSetup(b *strings.Builder, n *Node) {
	if setup := n.setupManager(); setup != "" {
		b.WriteString(setup + "\n")
	}
}

// renderStatic builds a site and serves it with nginx.
//
// Building inside Docker rather than on the host is deliberate: it means an
// operator needs no Node toolchain installed to deploy a Next.js or Vite
// site, and every build is reproducible.
func (r *Result) renderStatic() ([]byte, error) {
	output := r.Output
	if output == "" {
		return nil, fmt.Errorf("publix does not know which directory this build emits; set build.output in deployment.yaml")
	}

	var b strings.Builder
	b.WriteString(header(r.Name))

	switch {
	case r.Node != nil && (r.Build != "" || r.Install != ""):
		n := r.Node
		fmt.Fprintf(&b, "\nFROM %s AS build\nWORKDIR /app\n", r.Builder)
		writeManagerSetup(&b, n)
		fmt.Fprintf(&b, "%s\nRUN %s\n", n.lockfileCopy(), n.Install)
		b.WriteString("COPY . .\n")
		b.WriteString("ENV NODE_ENV=production CI=1 NEXT_TELEMETRY_DISABLED=1 ASTRO_TELEMETRY_DISABLED=1\n")
		if r.Build != "" {
			fmt.Fprintf(&b, "RUN %s\n", r.Build)
		}
		fmt.Fprintf(&b, "\nFROM %s AS runtime\n", staticImage(r))
		b.WriteString("COPY nginx.publix.conf /etc/nginx/conf.d/default.conf\n")
		fmt.Fprintf(&b, "COPY --from=build /app/%s /usr/share/nginx/html\n", strings.TrimPrefix(output, "./"))

	case r.Build != "" || r.Install != "":
		// A build command with no recognised toolchain: Hugo, Jekyll, a
		// Makefile. publix cannot guess what image runs it, and silently
		// skipping the command would ship an empty site.
		if r.Builder == "" {
			return nil, fmt.Errorf("build.builder is required: publix does not know which image runs %q. Set build.builder to an image with your toolchain, for example \"hugomods/hugo:exts\" or \"ruby:3.3\"", firstNonEmptyStr(r.Build, r.Install))
		}
		fmt.Fprintf(&b, "\nFROM %s AS build\nWORKDIR /app\nCOPY . .\n", r.Builder)
		if r.Install != "" {
			fmt.Fprintf(&b, "RUN %s\n", r.Install)
		}
		if r.Build != "" {
			fmt.Fprintf(&b, "RUN %s\n", r.Build)
		}
		fmt.Fprintf(&b, "\nFROM %s AS runtime\n", staticImage(r))
		b.WriteString("COPY nginx.publix.conf /etc/nginx/conf.d/default.conf\n")
		fmt.Fprintf(&b, "COPY --from=build /app/%s /usr/share/nginx/html\n", strings.TrimPrefix(output, "./"))

	default:
		// Files already in the repository, with nothing to build.
		fmt.Fprintf(&b, "\nFROM %s AS runtime\n", staticImage(r))
		b.WriteString("COPY nginx.publix.conf /etc/nginx/conf.d/default.conf\n")
		fmt.Fprintf(&b, "COPY %s /usr/share/nginx/html\n", strings.TrimPrefix(output, "./"))
	}

	fmt.Fprintf(&b, "EXPOSE %d\n", r.Port)
	return []byte(b.String()), nil
}

func staticImage(r *Result) string {
	if r.Runtime != "" && strings.HasPrefix(r.Runtime, "nginx") {
		return r.Runtime
	}
	return staticRuntime
}

// renderGo compiles a static binary and runs it on a minimal base.
func (r *Result) renderGo() ([]byte, error) {
	var b strings.Builder
	b.WriteString(header(r.Name))

	fmt.Fprintf(&b, "\nFROM %s AS build\nWORKDIR /src\n", r.Builder)
	// Module downloads are their own layer, so they survive a code change.
	b.WriteString("COPY go.mod go.sum* ./\nRUN go mod download\n")
	b.WriteString("COPY . .\n")
	b.WriteString("ENV CGO_ENABLED=0 GOOS=linux\n")
	fmt.Fprintf(&b, "RUN %s\n", r.Build)

	fmt.Fprintf(&b, "\nFROM %s AS runtime\n", r.Runtime)
	// Copy the CA bundle from the build stage rather than installing it:
	// the builder already has one, and reaching for a package manager here
	// would make every Go build depend on a route to a distro mirror.
	//
	// Zone data is deliberately not copied — the alpine builder has none —
	// so a service needing time zones should import _ "time/tzdata", which
	// embeds them in the binary and works anywhere.
	b.WriteString("COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt\n")
	b.WriteString("WORKDIR /app\nCOPY --from=build /out/server /app/server\n")
	// A numeric UID needs no user database, so this works on any base.
	b.WriteString("USER 10001:10001\n")
	fmt.Fprintf(&b, "ENV PORT=%d\nEXPOSE %d\n", r.Port, r.Port)
	b.WriteString("CMD [\"/app/server\"]\n")
	return []byte(b.String()), nil
}

// renderPython installs dependencies into a virtualenv and copies it into a
// clean runtime stage, so build tooling never reaches the final image.
func (r *Result) renderPython() ([]byte, error) {
	if r.Start == "" {
		return nil, fmt.Errorf("publix does not know how to start this app; set build.start in deployment.yaml")
	}

	var b strings.Builder
	b.WriteString(header(r.Name))

	fmt.Fprintf(&b, "\nFROM %s AS build\n", r.Builder)
	b.WriteString("ENV PIP_DISABLE_PIP_VERSION_CHECK=1 PYTHONDONTWRITEBYTECODE=1\n")
	b.WriteString("WORKDIR /app\n")
	b.WriteString("RUN python -m venv /opt/venv\nENV PATH=\"/opt/venv/bin:$PATH\"\n")
	b.WriteString("COPY requirements*.txt pyproject.toml* poetry.lock* uv.lock* setup.py* setup.cfg* ./\n")
	fmt.Fprintf(&b, "RUN %s\n", r.Install)
	b.WriteString("COPY . .\n")
	if r.Build != "" {
		fmt.Fprintf(&b, "RUN %s\n", r.Build)
	}

	fmt.Fprintf(&b, "\nFROM %s AS runtime\n", r.Runtime)
	b.WriteString("ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PATH=\"/opt/venv/bin:$PATH\"\n")
	b.WriteString("RUN useradd --create-home --uid 10001 app\nWORKDIR /app\n")
	b.WriteString("COPY --from=build /opt/venv /opt/venv\nCOPY --from=build /app /app\n")
	b.WriteString("USER app\n")
	fmt.Fprintf(&b, "EXPOSE %d\n", r.Port)
	fmt.Fprintf(&b, "CMD [\"sh\", \"-c\", %s]\n", quote(r.Start))
	return []byte(b.String()), nil
}

// NginxConf is the static-site server configuration that accompanies a
// generated static Dockerfile.
func (r *Result) NginxConf() []byte {
	fallback := "=404"
	if r.SPA {
		fallback = "/index.html"
	}
	port := r.Port
	if port == 0 {
		port = 80
	}
	return []byte(fmt.Sprintf(`# Generated by publix.
server {
    listen %d;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml image/svg+xml;
    gzip_min_length 1024;

    # Fingerprinted assets are safe to cache forever. HTML is not: caching
    # it would mean a deploy is invisible until the browser cache expires.
    location ~* \.(js|css|woff2?|png|jpg|jpeg|gif|svg|ico|webp|avif|map)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri %s;
    }

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ %s;
    }
}
`, port, fallback, fallback))
}

// quote renders a string as a JSON/Dockerfile-safe double-quoted literal.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

func firstNonEmptyStr(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}
